spring:
  profiles:
    active: dev
  devtools.restart.enabled: true
  thymeleaf.cache: false
  http.encoding.force: true
  http.encoding.charset: UTF-8
  http.encoding.enabled: true
  datasource:
    tomcat:
      remove-abandoned: true
      test-on-borrow: true
      validation-query: SELECT 1
      remove-abandoned-timeout: 60
      time-between-eviction-runs-millis: 60000

#  配置静态资源的路径
#
spring.mvc.static-path-pattern: /static/**
#  jpa:
#      database: POSTGRESQL
#      show-sql: true
#spring.datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://119.23.251.152:5432/postgres
#    username: postgres
#    password: 8525233

#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/matsim?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
#spring.datasource.username: root
#spring.datasource.password: 8525233
#spring.datasource.max-idle: 10
#spring.datasource.max-wait: 10000
#spring.datasource.min-idle: 5
#spring.datasource.initial-size: 5

spring.datasource.driver-class-name: net.postgis.jdbc.DriverWrapper
spring.datasource.url: jdbc:postgresql_postGIS://192.168.60.231:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.datasource.max-idle: 10
spring.datasource.max-wait: 10000
spring.datasource.min-idle: 5
spring.datasource.initial-size: 5

#    tomcat:
#      max-active: 20
##      initial-size: 1
##      min-idle: 1
#      max-wait: 60000
server:
  port: 7077
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 3
#    # Redis服务器地址
#    host: 172.16.1.159
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: 123456
#    # 连接超时时间（毫秒）
#    timeout: 5000

#logging.config: classpath:log4j2.xml


